[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["@prisma/adapter-libsql", "@libsql/client"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect non-www to www
[[redirects]]
  from = "https://examina.ink/*"
  to = "https://www.examina.ink/:splat"
  status = 301
  force = true
