import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { pageMetadata } from "@/lib/seo";
import KeywordLanding from "@/components/KeywordLanding";
import { EXAMS, getExam } from "@/lib/seo/exams";
import { copyText, saleCopy, saleLandingData, planOffers } from "@/lib/pricing";

export const dynamic = "force-static";
export const revalidate = 60;

export async function generateStaticParams() {
  return EXAMS.map((exam) => ({ exam: exam.slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ exam: string }> }): Promise<Metadata> {
  const { exam: examSlug } = await params;
  const exam = getExam(examSlug);
  if (!exam) return {};

  return pageMetadata({
    title: `${exam.name} Practice Test Generator — AI ${exam.name} Questions`,
    description: `Generate ${exam.name} practice questions with AI. ${exam.description} Free study tool.`,
    path: `/exams/${exam.slug}`,
  });
}

export default async function ExamPage({ params }: { params: Promise<{ exam: string }> }) {
  const { exam: examSlug } = await params;
  const exam = getExam(examSlug);
  if (!exam) notFound();

  const now = new Date();

  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `https://www.examina.ink/exams/${exam.slug}#webpage`,
        url: `https://www.examina.ink/exams/${exam.slug}`,
        name: `${exam.name} Practice Test Generator | Examina`,
        isPartOf: { "@id": "https://www.examina.ink/#website" },
      },
      {
        "@type": "SoftwareApplication",
        name: "Examina",
        url: "https://www.examina.ink",
        applicationCategory: "EducationalApplication",
        description: `${exam.name} practice question generator. ${exam.description}`,
        offers: planOffers(now),
      },
      {
        "@type": "FAQPage",
        mainEntity: exam.faq.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: copyText(saleCopy(f.a, now)) },
        })),
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Home",
            item: "https://www.examina.ink",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: "Exams",
            item: "https://www.examina.ink/exams",
          },
          {
            "@type": "ListItem",
            position: 3,
            name: exam.name,
            item: `https://www.examina.ink/exams/${exam.slug}`,
          },
        ],
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <KeywordLanding
        data={saleLandingData(
          {
            kicker: `${exam.fullName} Prep`,
            h1: `${exam.name} practice questions`,
            h1Accent: "generated by AI",
            subtitle: `${exam.description} Upload your study notes and get practice questions with explanations in seconds. ${exam.disclaimer}`,
            cta: "Generate practice questions",
            introTitle: `Why use AI for ${exam.name} practice?`,
            intro: [
              `Preparing for the ${exam.name} requires hours of practice with realistic questions. Creating those questions by hand is time-consuming and hard to do well—you need questions at the right difficulty, covering the right topics, with plausible wrong answers that expose real gaps in knowledge.`,
              `Examina generates ${exam.name}-style practice questions from your study material automatically. Upload your ${exam.name} prep book chapter, course notes, or review outline, and get multiple choice questions with explanations and Bloom's taxonomy tagging. Questions test the same skills as the real ${exam.name}, helping you identify weak areas before test day.`,
              ...(exam.topicsList
                ? [
                    `The ${exam.name} covers these content areas: ${exam.topicsList.join("; ")}. Upload notes from any of these topics to generate practice questions specific to what you're studying.`,
                  ]
                : []),
              `**Disclaimer:** ${exam.disclaimer}`,
            ],
            featuresTitle: "Built for effective practice",
            features: [
              {
                title: "Realistic practice questions",
                body: `Questions match ${exam.name} format and difficulty. Distractors (wrong answers) are based on common mistakes, not random words, making practice effective.`,
              },
              {
                title: "Detailed explanations",
                body: `Every question includes why the correct answer is right and what concepts you need to review if you miss it.`,
              },
              {
                title: "Track your progress",
                body: `Take practice quizzes multiple times and track your improvement. See which topics you've mastered and which need more work.`,
              },
            ],
            howTitle: `Sample ${exam.name} questions`,
            intro2: [
              `Here are examples of questions Examina can generate for ${exam.name} practice. Actual questions are based on your uploaded study material.`,
              ...(exam.questionTypesAdvice ? [`**Which question types work best:** ${exam.questionTypesAdvice}`] : []),
              ...(exam.studyTips
                ? [`**Study tips for ${exam.name} prep:** ${exam.studyTips.join(" ")}`]
                : []),
              exam.disclaimer,
            ],
            steps: exam.sampleQuestions.map((sq, i) => ({
              n: `0${i + 1}`,
              title: sq.q,
              body: `Answer: ${sq.a}. Explanation: ${sq.explanation}`,
            })),
            faqTitle: "Frequently asked questions",
            faq: exam.faq,
            relatedTitle: "Related tools",
            related: exam.relatedTools.map((href) => {
              const labels: Record<string, string> = {
                "/ai-quiz-generator": "AI Quiz Generator",
                "/multiple-choice-quiz-maker": "Multiple Choice Maker",
                "/quiz-generator-from-pdf": "PDF to Quiz",
                "/notes-to-quiz": "Notes to Quiz",
                "/study-guide-generator": "Study Guide Generator",
                "/ai-flashcards": "AI Flashcards",
                "/for-students": "For Students",
                "/vocabulary": "Vocabulary Quiz",
              };
              return { href, label: labels[href] || href };
            }),
          },
          now
        )}
      />
    </>
  );
}
