/**
 * Auto-extracted from new-subjects-2.ts
 */
import type { ComboData } from "./types";

export const AP_PSYCHOLOGY_COMBOS: ComboData[] = [
  {
    slug: "flashcards",
    type: "flashcards",
    meta: { type: "flashcards", primaryKeyword: "ap psychology flashcards", monthlyVolume: 880 },
    h1: "AP Psychology Flashcards — Master Psych Concepts for AP Exam",
    intro: "Build comprehensive AP Psychology knowledge with flashcards covering all nine units: biological bases, sensation/perception, learning, cognition, development, motivation/emotion, personality, abnormal psychology, treatment, and social psychology. Each card includes precise definitions, key researchers and studies, real-world application examples, and connections between concepts. Perfect for AP exam preparation focusing on both content knowledge and application to scenarios. Not affiliated with or endorsed by the College Board.",
    sampleItems: [
      { q: "Classical Conditioning", a: "Learning through association. Pavlov's dogs: bell (neutral stimulus) + food (unconditioned stimulus) → salivation. After repeated pairings, bell alone (conditioned stimulus) causes salivation (conditioned response).", explanation: "Classical conditioning explains reflexive/involuntary learning. Key: neutral stimulus becomes conditioned stimulus through repeated pairing with unconditioned stimulus. Also: acquisition, extinction, spontaneous recovery, generalization, discrimination.", bloomLevel: "Understand" },
      { q: "Piaget's Formal Operational Stage", a: "Age 12+ (adolescence to adulthood): abstract thinking, hypothetical reasoning, deductive logic, scientific thinking emerge. Example: can consider 'What if...?' scenarios, use systematic problem-solving, think about thinking (metacognition).", explanation: "Final Piaget stage. Not all adults fully develop formal operational thought (cultural variation). Contrast with concrete operational (7-11): literal, hands-on thinking only. Criticism: Piaget underestimated children's abilities.", bloomLevel: "Remember" },
      { q: "Neurotransmitter: Dopamine", a: "Functions: reward/pleasure, motivation, movement control. Too much: schizophrenia symptoms (hallucinations, delusions). Too little: Parkinson's disease (tremors). Drugs affecting: cocaine, amphetamines (increase), antipsychotics (block).", explanation: "Dopamine is central to brain reward pathway and addiction. Also regulates motor control (basal ganglia). Reward pathway: VTA → nucleus accumbens. Important for AP: know functions + disorders when levels abnormal.", bloomLevel: "Understand" },
      { q: "Cognitive Dissonance (Festinger)", a: "Mental discomfort from holding conflicting beliefs/behaviors. Resolution strategies: change belief, change behavior, or rationalize. Example: Smoker knows it's unhealthy (dissonance) → quits smoking OR rationalizes ('not that bad,' 'I exercise').", explanation: "Cognitive dissonance motivates attitude/behavior change to restore consistency. Classic study: Festinger & Carlsmith ($1/$20 experiment)—people paid $1 changed attitudes more than those paid $20 (insufficient justification). Important for AP.", bloomLevel: "Understand" },
      { q: "REM Sleep", a: "Rapid Eye Movement sleep: vivid dreams, paralysis (except eyes/diaphragm), brain activity similar to waking. Function: memory consolidation (especially procedural), emotional regulation. Deprived → REM rebound (catch-up).", explanation: "REM sleep paradox: brain active, body paralyzed. Occurs in 90-minute cycles, increasing in duration across night. REM deprivation impairs memory. Contrast with NREM stages (3 stages, deepest = Stage 3/delta waves).", bloomLevel: "Understand" },
      { q: "Operant Conditioning (Skinner)", a: "Learning through consequences. Reinforcement increases behavior (positive = add pleasant, negative = remove unpleasant). Punishment decreases behavior (positive = add unpleasant, negative = remove pleasant). Schedules: fixed/variable ratio/interval.", explanation: "Operant conditioning: voluntary behavior shaped by outcomes. Skinner box experiments. Reinforcement strengthens, punishment weakens. Key for AP: distinguish positive/negative reinforcement/punishment. Variable ratio = most resistant to extinction (slot machines).", bloomLevel: "Understand" },
      { q: "Erikson's Identity vs Role Confusion", a: "Stage 5 (adolescence, 12-18): develop sense of self and personal identity. Success → fidelity (commitment to identity). Failure → role confusion, identity crisis. Question: 'Who am I?'", explanation: "One of Erikson's 8 psychosocial stages. Contrast with Marcia's identity statuses (achievement, moratorium, foreclosure, diffusion). Adolescence = identity formation critical period. For AP: know all 8 Erikson stages.", bloomLevel: "Remember" },
      { q: "Schizophrenia", a: "Severe disorder with positive symptoms (hallucinations, delusions, disorganized speech/behavior) and negative symptoms (flat affect, social withdrawal, lack of motivation). Dopamine hypothesis: excess dopamine activity. Onset: late teens/early 20s.", explanation: "Schizophrenia ≠ multiple personalities (that's dissociative identity disorder). Biological basis: genetics, brain structure (enlarged ventricles), neurotransmitters. Treatment: antipsychotics (dopamine antagonists). For AP: distinguish positive/negative symptoms.", bloomLevel: "Understand" },
      { q: "Confirmation Bias", a: "Tendency to search for, interpret, and remember information that confirms preexisting beliefs while ignoring contradictory evidence. Example: Only reading news that agrees with your political views.", explanation: "Confirmation bias is a cognitive bias affecting reasoning and decision-making. Related: belief perseverance (maintaining beliefs despite disconfirming evidence). Important for understanding flawed thinking and pseudoscience acceptance.", bloomLevel: "Apply" },
      { q: "Maslow's Hierarchy of Needs", a: "Pyramid: physiological (base) → safety → love/belonging → esteem → self-actualization (peak). Lower needs must be met before higher needs motivate. Self-actualization: fulfilling potential.", explanation: "Maslow's humanistic theory of motivation. Criticism: not everyone follows hierarchy (artists starving for their work). Cultural variation: collectivist cultures may prioritize belonging over self-actualization. For AP: know order and examples of each level.", bloomLevel: "Remember" },
      { q: "Milgram's Obedience Study", a: "Participants administered (fake) shocks to learner at authority's command. 65% went to maximum 450V despite learner's screams. Demonstrated power of obedience to authority, even when harming others.", explanation: "Milgram's study showed situational factors (authority, proximity, legitimacy) override personal morals. Ethical concerns: deception, psychological harm. Explains how ordinary people commit atrocities. For AP: know procedure, results, ethical issues, and implications.", bloomLevel: "Understand" },
      { q: "Wernicke's Area", a: "Brain region (left temporal lobe) responsible for language comprehension. Damage → Wernicke's aphasia: fluent but meaningless speech, poor comprehension. Contrast: Broca's area (production).", explanation: "Wernicke's area: understanding language. Broca's area: producing language. Damage to Wernicke's = can speak but doesn't make sense or understand. For AP: distinguish Broca's vs Wernicke's aphasia symptoms and locations.", bloomLevel: "Remember" },
    ],
    topicsCovered: ["Biological bases (brain, neurons, neurotransmitters, endocrine)", "Sensation and perception", "Learning (classical, operant, observational)", "Cognition (memory, thinking, language, intelligence)", "Development (Piaget, Erikson, Kohlberg, attachment)", "Motivation and emotion", "Personality (psychoanalytic, humanistic, trait, social-cognitive)", "Abnormal psychology (disorders: anxiety, mood, schizophrenia, dissociative, personality)", "Treatment approaches (psychoanalytic, humanistic, behavioral, cognitive, biomedical)", "Social psychology (attribution, conformity, obedience, group behavior, prejudice)"],
    studyTips: {
      workflow: ["Study 15-20 psychology flashcards daily—distributed practice beats cramming", "Group cards by unit to build thematic understanding and see connections", "Apply concepts to real-world examples to deepen learning and improve retention", "Test yourself actively—don't just read, try to recall before flipping", "Focus extra time on units you find hardest (commonly: biological bases, research methods, statistics)"],
      tips: ["Know key researchers and their contributions (Pavlov, Skinner, Freud, Piaget, Erikson, Kohlberg, Milgram, Zimbardo, Asch, etc.) cold", "Understand research methods—AP Psych tests experimental design, validity, reliability, ethics heavily on FRQs", "Connect biological and psychological levels of analysis—how do brain/neurotransmitters relate to behavior/cognition?", "Distinguish similar concepts: classical vs operant conditioning, Broca's vs Wernicke's aphasia, positive vs negative reinforcement/punishment", "Learn vocabulary precisely—psychology is a technical field with specific terminology", "Practice FRQ writing separately—knowing content isn't enough, must communicate clearly and use correct terms"],
    },
    faq: [
      { q: "What AP Psychology units are covered in flashcards?", a: "All nine units: biological bases, sensation/perception, learning, cognition, development, motivation/emotion, personality, abnormal psychology, treatment, and social psychology. Balanced coverage aligned with AP exam weighting." },
      { q: "Do cards include classic research studies?", a: "Yes. Cards reference essential studies (Milgram obedience, Zimbardo prison, Asch conformity, Little Albert, Harlow's monkeys, etc.) and key researchers' contributions. Know procedures, results, and implications." },
      { q: "Are flashcards sufficient for AP exam prep?", a: "Flashcards build foundational knowledge (crucial for multiple choice). Also practice FRQs (free response questions) from official College Board materials to develop writing skills. Combine content mastery with application practice." },
      { q: "How do I remember all the psychologists and theories?", a: "Create associations: Pavlov's dogs, Skinner's box, Freud's couch. Group by topic: all learning theorists together, all developmental theorists together. Use mnemonics for lists (e.g., Freud's psychosexual stages: 'Oh Larry, Please Go Away' = Oral, Latency, Phallic, Genital, Anal)." },
    ],
    relatedPages: ["/exams/ap-psychology", "/subjects/psychology", "/exams/mcat/flashcards", "/ai-flashcards"],
  },
];
