/**
 * Auto-extracted from new-subjects-2.ts
 */
import type { ComboData } from "./types";

export const AP_US_HISTORY_COMBOS: ComboData[] = [
  {
    slug: "practice-questions",
    type: "practice-questions",
    meta: { type: "practice-questions", primaryKeyword: "apush practice questions", secondaryKeywords: ["apush practice test", "apush questions", "apush multiple choice questions"], monthlyVolume: 6600 },
    h1: "APUSH Practice Questions — AP US History Exam Prep",
    intro: "Master AP US History with comprehensive practice questions covering all nine periods (1491-present), historical thinking skills, thematic connections, and AP-style question formats. Each question includes detailed explanations of historical concepts, causation, contextualization, and comparison. Perfect for AP exam preparation, focusing on stimulus-based reasoning and historical argumentation. Not affiliated with or endorsed by the College Board.",
    sampleItems: [
      { q: "Which development best represents the shift from Jeffersonian to Hamiltonian economic policy?", a: "The establishment of the Second Bank of the United States (1816)", explanation: "The Second Bank represented federal economic intervention, aligning with Hamilton's vision of strong central government and national banking rather than Jefferson's agrarian idealism and states' rights. This shift occurred after War of 1812 exposed economic weaknesses.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "How did the Second Great Awakening influence antebellum reform?", a: "It emphasized individual moral responsibility, inspiring temperance, abolitionist, and women's rights movements", explanation: "Religious revival (1790s-1840s) stressed personal salvation and moral improvement, motivating social reform causes. Idea that society could be perfected through individual moral action drove reforms in education, prisons, asylums, temperance, abolition, women's rights.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "True or False: The Monroe Doctrine (1823) immediately stopped European colonization in the Americas.", a: "False", explanation: "False. The Monroe Doctrine was more symbolic than enforceable in 1823. The US lacked military power to enforce it until much later (late 19th century). British Navy actually enforced it indirectly. Became important precedent for later US intervention.", bloomLevel: "Understand", type: "true-false" },
      { q: "What was the primary goal of the Interstate Commerce Act (1887)?", a: "Regulate railroad rates and practices to protect farmers and small businesses from monopoly abuses", explanation: "The ICC (Interstate Commerce Commission) was the first federal regulatory agency, created to address railroad monopoly abuses like rebates, pooling, and discriminatory rates. Marked shift toward federal economic regulation in Gilded Age.", bloomLevel: "Remember", type: "multiple-choice" },
      { q: "Which factor most contributed to the Great Migration (1916-1970)?", a: "Industrial job opportunities in Northern cities and escape from Jim Crow segregation", explanation: "Great Migration saw 6+ million African Americans move from rural South to urban North/West. Driven by both 'push' (Jim Crow, violence, lack of opportunity) and 'pull' (industrial jobs in WWI/WWII, greater freedom). Transformed American demographics and culture.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "How did the New Deal fundamentally change the role of federal government?", a: "Established government responsibility for economic security and social welfare (modern welfare state)", explanation: "New Deal (1933-1939) created Social Security, unemployment insurance, labor protections, financial regulations. Marked permanent expansion of federal power into economic/social realm. Conservative opposition argued it violated limited government principles.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "Compare Reconstruction (1865-1877) outcomes for freedpeople with post-WWII outcomes for African Americans.", a: "Both periods saw initial progress followed by retrenchment, but post-WWII gains (Civil Rights Movement) proved more durable", explanation: "Reconstruction: 13th-15th Amendments, Black political participation, then Jim Crow backlash. Post-WWII: Brown v. Board, Civil Rights Act, Voting Rights Act, with resistance but lasting legal changes. Economic gains also greater in 20th century.", bloomLevel: "Evaluate", type: "multiple-choice" },
      { q: "True or False: The Progressive Era (1890s-1920s) exclusively benefited industrial workers and immigrants.", a: "False", explanation: "False. Progressive reforms had mixed effects. While some helped workers (labor laws, safety regulations), other reforms restricted immigrants (quotas, Americanization) and excluded African Americans (ignored by most white progressives). Reforms also limited democracy via expert commissions.", bloomLevel: "Evaluate", type: "true-false" },
      { q: "What continuity persisted from Gilded Age through Progressive Era despite reform efforts?", a: "Economic inequality and corporate power remained despite regulatory attempts", explanation: "Despite ICC, Sherman Antitrust Act, and Progressive reforms, large corporations (trusts) continued to dominate economy. Some monopolies broken up, but big business influence persisted. Also: racial inequality continued despite reform rhetoric.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "How did US foreign policy change from 1890s through WWI?", a: "From continental expansion to overseas imperialism to reluctant global involvement", explanation: "1890s: Spanish-American War, Philippines, Hawaii (imperialism). 1900-1914: Dollar Diplomacy, Panama Canal (intervention). 1917-1918: Enter WWI (shift from neutrality to intervention). Rejected League of Nations but emerged as world power.", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "Which New Deal program had the most lasting impact on American society?", a: "Social Security (created permanent federal role in retirement security)", explanation: "Social Security Act (1935) created federal old-age insurance still central today. Other lasting programs: FDIC (bank insurance), SEC (financial regulation), NLRB (labor), TVA (regional development). Agricultural and work relief programs ended.", bloomLevel: "Evaluate", type: "multiple-choice" },
      { q: "Contextualize the Cold War: What post-WWII conditions led to US-Soviet conflict?", a: "Ideological differences (capitalism vs communism), power vacuum in Europe/Asia, mutual distrust from WWII, atomic weapons", explanation: "Cold War emerged from: (1) incompatible ideologies, (2) both superpowers filling power vacuum left by WWII, (3) Soviet expansion in Eastern Europe vs US containment, (4) nuclear arms race creating existential stakes. Not inevitable but likely given circumstances.", bloomLevel: "Analyze", type: "multiple-choice" },
    ],
    topicsCovered: ["Period 1: Pre-Columbian to 1607", "Period 2: Colonial America 1607-1754", "Period 3: Revolution and Early Republic 1754-1800", "Period 4: Jeffersonian Era to Manifest Destiny 1800-1848", "Period 5: Civil War and Reconstruction 1844-1877", "Period 6: Gilded Age and Imperialism 1865-1898", "Period 7: Progressive Era through WWI 1890-1920", "Period 8: 1920s through WWII 1920-1945", "Period 9: Cold War to Present 1945-present", "Historical thinking skills: causation, comparison, continuity/change, contextualization, argumentation"],
    studyTips: {
      workflow: ["Take timed practice tests to simulate AP exam conditions (55 min for 55 MCQs)", "Review explanations focusing on causation, comparison, and historical thinking—not just facts", "Connect events across themes (politics, economics, culture, technology, demographics)", "Practice DBQ and LEQ separately from multiple choice—different skills", "Use wrong answers to identify content gaps and review those periods/themes"],
      tips: ["Master periodization—understand what defines each of the 9 AP periods and turning points between them", "Practice SAQ, DBQ, and LEQ skills separately from multiple choice—writing requires different preparation", "Focus on causation: how one event led to another across periods (long-term and short-term causes)", "Learn to contextualize: what broader historical developments surround each event?", "Compare across time periods: how did industrialization in Gilded Age differ from early 19th century? How was Cold War like earlier ideological conflicts?", "Use AP Historical Thinking Skills: Causation, Comparison, Continuity & Change, Contextualization, Synthesis", "Don't just memorize facts—understand relationships, patterns, and arguments historians make"],
    },
    faq: [
      { q: "Are these real AP exam questions?", a: "No. These are original practice questions following official AP US History format and testing the same skills. For official released exams, visit College Board AP Central." },
      { q: "What APUSH periods are covered?", a: "All nine periods (1491-present) with balanced coverage. Questions emphasize thematic connections (politics, economics, culture, technology) and historical thinking skills (causation, comparison, continuity/change) required by AP exam." },
      { q: "Do questions match AP exam difficulty and format?", a: "Yes. Questions test the same analytical skills and content depth as actual AP US History exam. Mix of stimulus-based (primary sources, charts, images) and standalone questions, matching AP format." },
      { q: "How should I study for APUSH?", a: "Focus on understanding causes and effects, not just memorizing dates. Practice historical thinking skills. Take full practice exams under timed conditions. Review both content and skills." },
    ],
    relatedPages: ["/exams/ap-us-history", "/subjects/history", "/subjects/world-history/quiz", "/practice-test-generator"],
  },
];
