/**
 * Auto-extracted from new-subjects-1.ts
 */
import type { ComboData } from "./types";

export const GRAMMAR_COMBOS: ComboData[] = [
  {
    slug: "quiz",
    type: "quiz",
    meta: { type: "quiz", primaryKeyword: "grammar quiz", monthlyVolume: 1300 },
    h1: "Grammar Quiz — Test Your Grammar Knowledge",
    intro: "Master English grammar with comprehensive quizzes covering parts of speech, sentence structure, punctuation, verb tenses, pronoun usage, modifiers, and common errors. Test your understanding with real-world examples and immediate explanations. Perfect for middle school through adult learners, ESL students, SAT/ACT prep, or professional writing improvement.",
    sampleItems: [
      { q: "Identify the error: 'Me and him went to the park.'", a: "Should be 'He and I went to the park' (subject pronouns)", explanation: "Use subject pronouns (I, he, she, we, they) as sentence subjects. Object pronouns (me, him, her, us, them) follow verbs/prepositions. Tip: remove other person and test: 'Me went' sounds wrong, 'I went' sounds right.", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Which sentence uses commas correctly?", a: "'I bought apples, oranges, and bananas.' (Oxford comma)", explanation: "Use commas to separate items in a series. The Oxford comma (before 'and') prevents ambiguity. Without it, 'I thank my parents, Oprah and God' implies your parents ARE Oprah and God!", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Choose the correct verb: 'Neither the teacher nor the students ___ ready.'", a: "were (verb agrees with nearest subject)", explanation: "With 'neither...nor,' the verb agrees with the nearest subject (proximity agreement). 'Students' is plural, so use 'were.' If reversed ('neither the students nor the teacher'), use 'was.'", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "True or False: 'Who' is used for subjects, 'whom' for objects.", a: "True", explanation: "Who = subject (Who called?). Whom = object (To whom did you speak? Whom did you see?). Tip: if you'd answer with 'he,' use 'who'; if 'him,' use 'whom.' 'Whom' is becoming archaic in casual speech.", bloomLevel: "Understand", type: "true-false" },
      { q: "Identify the adverb: 'She sings beautifully.'", a: "Beautifully (modifies verb 'sings')", explanation: "Adverbs modify verbs, adjectives, or other adverbs. Many (not all) end in -ly. They answer how, when, where, or to what extent. 'Beautifully' tells HOW she sings.", bloomLevel: "Remember", type: "multiple-choice" },
      { q: "Fix the fragment: 'Because I was tired.'", a: "Add an independent clause: 'Because I was tired, I went to bed.' OR 'I went to bed because I was tired.'", explanation: "Subordinating conjunctions (because, although, if, when, while) create dependent clauses that need an independent clause to complete the sentence. Can't stand alone.", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Which sentence has correct apostrophe usage?", a: "'The dog's bone' (possessive singular) and 'The dogs' bones' (possessive plural)", explanation: "Apostrophes show possession. Singular: add 's (dog's). Plural ending in s: add only ' (dogs'). Plural not ending in s: add 's (children's). Never use apostrophes for regular plurals.", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Choose correct: 'Each of the students ___ their own book.' or 'Each of the students ___ his or her own book.'", a: "'Each of the students has his or her own book.' OR 'All students have their own books.' (avoid singular they with 'each')", explanation: "'Each' is singular, so use 'has.' Traditionally 'his or her' for singular, but modern usage increasingly accepts singular 'they/their.' Rewrite to plural avoids issue.", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Identify the misplaced modifier: 'She served sandwiches to the children on paper plates.'", a: "Sounds like children were on plates. Fix: 'She served sandwiches on paper plates to the children.'", explanation: "Misplaced modifiers create confusion or unintended humor. Place modifiers next to what they modify. 'On paper plates' modifies 'sandwiches,' not 'children.'", bloomLevel: "Analyze", type: "multiple-choice" },
      { q: "True or False: 'Good' is an adjective, 'well' is an adverb.", a: "True (with exception: 'well' can be adjective meaning healthy)", explanation: "True. Good modifies nouns (good book). Well modifies verbs (sings well). Exception: 'I feel well' (healthy). But: 'I feel good' (happy/satisfied). Common error: 'She did good' should be 'She did well.'", bloomLevel: "Understand", type: "true-false" },
      { q: "Which is correct: 'Less people' or 'Fewer people'?", a: "'Fewer people' (countable)", explanation: "Use 'fewer' with countable nouns (fewer people, fewer books). Use 'less' with uncountable nouns (less water, less time). Common error: 'less items' should be 'fewer items.'", bloomLevel: "Apply", type: "multiple-choice" },
      { q: "Fix the run-on: 'I love grammar it's fascinating.'", a: "Options: (1) 'I love grammar. It's fascinating.' (2) 'I love grammar; it's fascinating.' (3) 'I love grammar, and it's fascinating.'", explanation: "Run-on sentences improperly join independent clauses. Fix with: (1) period, (2) semicolon, (3) comma + coordinating conjunction (FANBOYS: for, and, nor, but, or, yet, so), or (4) subordination.", bloomLevel: "Apply", type: "multiple-choice" },
    ],
    topicsCovered: ["Parts of speech (nouns, verbs, adjectives, adverbs, pronouns, prepositions)", "Sentence structure (fragments, run-ons, clauses)", "Punctuation rules (commas, apostrophes, semicolons)", "Subject-verb agreement", "Pronoun usage (case, antecedent agreement)", "Modifiers (placement, dangling/misplaced)", "Common errors", "Verb tenses"],
    studyTips: {
      workflow: ["Take grammar quiz to identify weak areas—diagnostic first, then study", "Review specific grammar rules you missed with detailed explanations and examples", "Practice applying rules in your own writing—find those errors in your essays", "Retake quiz after study to verify mastery and track progress", "Focus on ONE grammar rule at a time until automatic—don't try to learn everything at once"],
      tips: ["Read quality writing to internalize correct grammar patterns—good grammar becomes intuitive with exposure", "Learn one grammar rule at a time and master it before moving on—depth beats breadth", "Proofread your writing specifically for errors you commonly make—keep an error log", "Use grammar mnemonics: FANBOYS for coordinating conjunctions, I before E except after C for spelling", "Understand WHY rules exist—helps you remember and apply them to new situations", "Practice identifying parts of speech in real sentences—grammar is a tool for clear communication"],
    },
    faq: [
      { q: "What grammar topics are covered?", a: "Parts of speech, sentence structure (fragments, run-ons, clauses), punctuation (commas, apostrophes, semicolons), subject-verb agreement, verb tenses, pronoun usage, modifiers, and common errors like who/whom, good/well, fewer/less." },
      { q: "Is this suitable for ESL learners?", a: "Yes. Quizzes work for intermediate to advanced ESL students learning English grammar rules, as well as native speakers refining their skills. Explanations clarify rules that native speakers often apply intuitively." },
      { q: "Can I practice specific grammar rules?", a: "Yes. Upload notes on specific topics (e.g., 'subjunctive mood,' 'comma usage,' 'dangling modifiers') to generate focused quizzes on those rules only." },
      { q: "Why do I need good grammar?", a: "Clear grammar ensures your meaning is understood. Errors distract readers and undermine credibility. Strong grammar skills help in academic writing, professional communication, and standardized tests (SAT/ACT)." },
    ],
    relatedPages: ["/subjects/grammar", "/subjects/english/quiz", "/subjects/vocabulary/quiz", "/ai-quiz-generator"],
  },
];
