/**
 * Auto-extracted from new-subjects-1.ts
 */
import type { ComboData } from "./types";

export const SPELLING_COMBOS: ComboData[] = [
  {
    slug: "flashcards",
    type: "flashcards",
    meta: { type: "flashcards", primaryKeyword: "spelling flashcards", monthlyVolume: 1600 },
    h1: "Spelling Flashcards — Master Correct Spelling",
    intro: "Build spelling mastery with flashcards that show correct spellings, common misspellings, and memory aids. Perfect for weekly spelling lists, vocabulary building, or ESL learners working on English spelling patterns. Each card includes phonetic breakdowns and mnemonic devices to help you remember tricky words.",
    sampleItems: [
      { q: "Definitely", a: "D-E-F-I-N-I-T-E-L-Y (not definately). Memory aid: Remember FINITE is in the middle. Common error: replacing 'i' with 'a'.", explanation: "One of the most commonly misspelled words. Break it down: de-finite-ly. Never use 'a' in the middle.", bloomLevel: "Remember" },
      { q: "Separate", a: "S-E-P-A-R-A-T-E (not seperate). Memory aid: There's A RAT in separate. Common error: using 'e' instead of 'a' in middle.", explanation: "Remember: sep-A-rate. Think of the rat to recall the 'a'. Spell it with 'a', not 'e'.", bloomLevel: "Remember" },
      { q: "Embarrass", a: "E-M-B-A-R-R-A-S-S (two R's, two S's). Memory aid: Really, Really Should Stay Silent. Common errors: single R or single S.", explanation: "Double R, double S. Think: em-BARR-ASS. Both letters double—remember both!", bloomLevel: "Remember" },
      { q: "Occasion", a: "O-C-C-A-S-I-O-N (two C's, one S). Memory aid: two C's, one S. Common error: double S.", explanation: "Remember: oc-ca-sion. Double the C, single the S. Opposite of what you might think!", bloomLevel: "Remember" },
      { q: "Necessary", a: "N-E-C-E-S-S-A-R-Y (one C, two S's). Memory aid: one Collar, two Sleeves. Common error: double C or single S.", explanation: "NeCeSSary. Think of a shirt: 1 collar (C), 2 sleeves (SS). Visual memory trick works!", bloomLevel: "Remember" },
      { q: "Receive", a: "R-E-C-E-I-V-E ('i before e except after c'). Common error: writing recieve.", explanation: "The 'i before e except after c' rule applies here: re-CEI-ve. C comes before the ei pair.", bloomLevel: "Remember" },
      { q: "Accommodate", a: "A-C-C-O-M-M-O-D-A-T-E (two C's, two M's). Memory aid: This word has enough room to accommodate both double letters.", explanation: "Double C, double M. Remember: ac-com-mo-date. Both pairs of letters need extra room!", bloomLevel: "Remember" },
      { q: "Achievement", a: "A-C-H-I-E-V-E-M-E-N-T ('i before e'). Common error: acheivment.", explanation: "Achieve + ment = achievement. 'I before e' rule applies (no c before it). Don't forget the middle 'e'.", bloomLevel: "Remember" },
      { q: "Conscience", a: "C-O-N-S-C-I-E-N-C-E. Memory aid: Your conscience needs SCIENCE. Common error: concience.", explanation: "Contains 'science' in the middle: con-SCIENCE. Remember the sci- pattern.", bloomLevel: "Remember" },
      { q: "Rhythm", a: "R-H-Y-T-H-M (no vowels except Y!). Memory aid: Rhythm Helps Your Two Hips Move.", explanation: "Unusual spelling—all consonants except Y. Think of the mnemonic: RHYTHM acronym.", bloomLevel: "Remember" },
      { q: "Weird", a: "W-E-I-R-D ('i before e' exception). Memory aid: 'We are weird.' Common error: wierd.", explanation: "Exception to 'i before e' rule. E comes first: WEIRD. Remember: weird breaks the rule!", bloomLevel: "Remember" },
      { q: "Maintenance", a: "M-A-I-N-T-E-N-A-N-C-E. Memory aid: Maintain + -ance, but keep the 'e'. Common error: maintenence.", explanation: "From 'maintain' + suffix '-ance'. Keep the root intact: main-ten-ance.", bloomLevel: "Remember" },
    ],
    topicsCovered: ["Commonly misspelled words", "Spelling patterns", "Homophones", "Word roots", "Memory strategies", "Grade-level vocabulary", "Silent letters", "Double consonants"],
    studyTips: {
      workflow: ["Study 10 spelling words daily using flashcards—consistency beats cramming", "Write each word 3 times to build muscle memory and reinforce letter patterns", "Test yourself by covering the answer and spelling aloud, then writing", "Focus extra practice on words you miss repeatedly—track your weak spots"],
      tips: ["Break long words into syllables or smaller chunks—'sep-a-rate' is easier than 'separate'", "Create personal mnemonics for words you consistently misspell—make them memorable or funny", "Practice words in context sentences, not isolation—spelling transfers better in real writing", "Learn spelling rules (i before e, doubling rules) to decode new words", "Keep a personal 'demons' list of words you always misspell and review it weekly"],
    },
    faq: [
      { q: "What spelling levels are covered?", a: "Elementary through high school spelling lists, plus commonly misspelled adult words like 'definitely', 'separate', and 'accommodate'. Upload grade-level curriculum or create custom lists." },
      { q: "Can I upload my weekly spelling list?", a: "Yes. Paste or upload any word list to generate flashcards with memory aids, common errors, and mnemonic devices tailored to your words." },
      { q: "Do cards include pronunciation?", a: "Cards show phonetic spelling and syllable breaks to help with pronunciation. Especially helpful for ESL learners and auditory learners." },
      { q: "How do I study most effectively?", a: "Use spaced repetition: study new words daily, review missed words every 3 days, then weekly. Writing words by hand (not typing) builds stronger memory." },
    ],
    relatedPages: ["/subjects/spelling", "/subjects/spelling/worksheet-generator", "/subjects/vocabulary/flashcards", "/ai-flashcards"],
  },
  {
    slug: "worksheet-generator",
    type: "worksheet-generator",
    meta: { type: "worksheet-generator", primaryKeyword: "spelling worksheet generator", monthlyVolume: 1600 },
    h1: "Spelling Worksheet Generator — Create Custom Practice Sheets",
    intro: "Generate spelling worksheets with word lists, sentences, and answer keys. Perfect for teachers creating weekly spelling homework, parents supporting home practice, or students wanting independent spelling practice. Create worksheets that match your curriculum, grade level, and learning focus.",
    sampleItems: [
      { q: "Sample Worksheet: Grade 3 Spelling - Long A Sounds", a: "Words: make, cake, take, snake, grade, trade, brave, wave, escape, parade. Sentences: 1) Fill in: The ___ is in the lake. 2) Use 'brave' in a sentence. 3) Sort words by pattern: a_e words.", explanation: "Worksheet focuses on 'a_e' long A pattern (magic e). Includes word list, fill-in-blanks, sentence writing, and pattern recognition.", bloomLevel: "Apply" },
      { q: "Sample Worksheet: Grade 5 - Double Consonants", a: "Words: happen, butter, sitting, running, summer, dinner, letter, better, happened, swimming. Activity: Sort words by which letter doubles (pp, tt, nn, mm). Explain when to double.", explanation: "Teaches doubling rule: when adding -ing or -ed to CVC words, double the final consonant. Includes sorting and rule application.", bloomLevel: "Understand" },
      { q: "Sample Worksheet: Grade 7 - Homophones", a: "Words: their/there/they're, to/two/too, your/you're, its/it's, then/than. Fill in correct word: ___ going to ___ house. Write sentences using each correctly.", explanation: "Practice distinguishing common homophones in context. Includes usage explanations and sentence writing to cement understanding.", bloomLevel: "Apply" },
      { q: "Sample Worksheet: Grade 4 - Prefixes (un-, re-, pre-)", a: "Words: unhappy, redo, preview, uncertain, replay, preschool, unfair, rewrite, preheat. Match prefix to meaning. Add prefix to base words. Use in sentences.", explanation: "Teaches prefix meanings and how they change word meaning. Build vocabulary by understanding word parts.", bloomLevel: "Analyze" },
      { q: "Sample Worksheet: Grade 6 - Spelling Demons", a: "Words: separate, definitely, accommodate, necessary, embarrass, conscience. Write word 3x. Identify common misspelling. Create mnemonic device.", explanation: "Focus on frequently misspelled words with mnemonic creation activity. Students create personal memory aids.", bloomLevel: "Create" },
      { q: "Sample Worksheet: Grade 2 - CVC Words", a: "Words: cat, bat, sit, hit, dog, log, run, fun, bed, red. Circle the vowel. Change first letter to make new word (cat→bat). Write rhyming words.", explanation: "Consonant-Vowel-Consonant pattern practice. Foundation for decoding and encoding skills.", bloomLevel: "Apply" },
      { q: "Sample Worksheet: Grade 8 - Greek/Latin Roots", a: "Words: biology, photograph, telescope, sympathy, automatic. Underline the root. Write meaning of root (bio=life, photo=light, tele=far, etc). Find 2 more words with each root.", explanation: "Etymology and word-building using Greek/Latin roots. Expands vocabulary by understanding word origins.", bloomLevel: "Analyze" },
      { q: "Sample Worksheet: Kindergarten - Sight Words", a: "Words: the, and, is, it, in, on, at, for, you, me. Trace each word 2x. Find word in sentence. Write word from memory.", explanation: "High-frequency sight word practice with tracing, recognition, and recall. Foundation for reading fluency.", bloomLevel: "Remember" },
      { q: "Sample Worksheet: Grade 5 - Silent Letters", a: "Words: knight, wrench, gnome, thumb, knee, write, knife, comb. Circle the silent letter. Sort by which letter is silent (k, w, g, b). Use in sentences.", explanation: "Identify and practice words with silent letters. Pattern recognition helps predict spelling.", bloomLevel: "Understand" },
      { q: "Sample Worksheet: Grade 7 - -ible vs -able endings", a: "Words: possible, terrible, comfortable, acceptable, responsible, affordable. Sort by ending. Identify base word. Learn the rule: -able more common, -ible after hard c/g.", explanation: "Tricky suffix distinction with pattern analysis. Learn when to use which ending.", bloomLevel: "Analyze" },
    ],
    topicsCovered: ["Grade-level word lists", "Phonics patterns", "Word families", "Sight words", "Homophones", "Prefixes and suffixes", "Silent letters", "Double consonants", "Greek and Latin roots"],
    studyTips: {
      workflow: ["Generate worksheet for current spelling list at start of week", "Complete worksheet independently—don't look at answer key first", "Check answers and circle missed words", "Practice only missed words with additional worksheets", "Retake original worksheet to verify mastery"],
      tips: ["Do worksheets multiple times with different sentences for the same words—varied practice builds transfer", "Focus on words you miss—don't waste time on words you already know cold", "Use worksheets for pretest Friday, study over weekend, final test Monday rhythm", "Write neatly—sloppy handwriting causes self-correction errors", "Time yourself to build automaticity—spelling should become quick and effortless"],
    },
    faq: [
      { q: "What grade levels are supported?", a: "Kindergarten through 8th grade spelling worksheets matching typical curriculum standards and Common Core expectations. Also ESL and adult learner levels." },
      { q: "Can I customize word lists?", a: "Yes. Upload your school's spelling curriculum, textbook word lists, or create fully custom lists with your chosen words and difficulty." },
      { q: "Do worksheets include answer keys?", a: "Yes. Every worksheet has an answer key for checking work. Teachers can choose to hide answers for student copies." },
      { q: "What worksheet formats are available?", a: "Word lists, fill-in-the-blank sentences, ABC order, word searches, crosswords, word sorts, sentence writing, proofreading, and more—all generated automatically." },
    ],
    relatedPages: ["/subjects/spelling", "/subjects/spelling/flashcards", "/features/worksheet-generator", "/for-teachers"],
  },
  {
    slug: "quiz-generator",
    type: "quiz-generator",
    meta: { type: "quiz-generator", primaryKeyword: "spelling test generator", secondaryKeywords: ["spelling quiz generator", "spelling quiz maker"], monthlyVolume: 880 },
    h1: "Spelling Test Generator — Create Custom Spelling Tests",
    intro: "Generate spelling tests with customizable word lists, difficulty levels, and formats. Perfect for weekly classroom spelling tests, homeschool assessments, or self-study verification. Create pretests to identify gaps and final tests to measure mastery. Choose from traditional oral/written format, multiple choice, fill-in-blank, error detection, or full sentence dictation. Each test includes answer keys and optional grading rubrics. Tailor word lists to your grade level, curriculum, or personal spelling demons list.",
    sampleItems: [
      { q: "Sample Test Format: Traditional Spelling Test", a: "Teacher reads word, uses it in sentence, student writes word. Example: 'Necessary - It is necessary to study. Necessary.' Graded for correct spelling.", explanation: "Classic format: oral administration, written response. Tests listening and spelling together. Most common classroom format.", bloomLevel: "Apply" },
      { q: "Sample Test Format: Multiple Choice", a: "Which is correct? A) definately B) definetly C) definitely D) definitly. Answer: C", explanation: "Multiple choice tests recognition of correct spelling among common errors. Easier than recall—good for initial assessment.", bloomLevel: "Remember" },
      { q: "Sample Test Format: Fill-in-the-Blank", a: "Complete: I ___ went to the store yesterday. (definitely). Test spelling in context.", explanation: "Context-based spelling tests comprehension and spelling together. Closer to real writing scenarios.", bloomLevel: "Apply" },
      { q: "Sample Test Format: Error Detection", a: "Find and correct the misspelling: 'I definately need to study for the test.' (definitely)", explanation: "Proofreading format mirrors real editing tasks. Requires recognition and correction skills.", bloomLevel: "Evaluate" },
      { q: "Sample Test Format: Dictation Sentences", a: "Write full sentence from dictation: 'The necessary accommodations were provided.' Tests multiple words in context.", explanation: "Full-sentence dictation tests spelling, punctuation, and grammar together. Advanced format.", bloomLevel: "Apply" },
      { q: "Sample Test Format: Word Sorting", a: "Sort words by pattern: separate, desperate, temperate | celebrate, demonstrate, elaborate. Rule: -ate ending patterns.", explanation: "Pattern recognition format. Tests understanding of spelling rules, not just memorization.", bloomLevel: "Analyze" },
      { q: "Sample Test Format: Missing Letters", a: "Fill in missing letters: sep_r_te, n_c_ss_ry, d_fin_t_ly. Answers: separate, necessary, definitely.", explanation: "Partial-cue format focuses on problem spots. Good for targeted practice of tricky letter sequences.", bloomLevel: "Apply" },
      { q: "Sample Test Format: Homophone Choice", a: "Choose correct word: Their/There/They're going to ___ house over ___. Answers: their, there.", explanation: "Tests meaning-based spelling distinction. Requires understanding usage, not just letter patterns.", bloomLevel: "Understand" },
      { q: "Sample Test Format: Prefix/Suffix Building", a: "Add prefix/suffix: happy → ___ (unhappy), view → ___ (preview), play → ___ (replayed). Spell correctly.", explanation: "Tests spelling of word parts and combining rules (doubling, y→i, etc.). Builds word analysis skills.", bloomLevel: "Apply" },
      { q: "Sample Test Format: Rhyming Spelling", a: "Spell a word that rhymes with 'night' and means a soldier: ___ (knight). Tests spelling + vocabulary.", explanation: "Combined spelling and vocabulary format. Requires both word knowledge and orthography.", bloomLevel: "Apply" },
    ],
    topicsCovered: ["Custom word lists", "Multiple test formats", "Difficulty levels", "Answer keys", "Grading rubrics", "Pretests and posttests"],
    studyTips: {
      workflow: ["Generate pretest Monday to identify words to study—don't study first, test cold", "Analyze results: which words did you miss? What patterns (silent letters, double consonants)?", "Study only missed words during week using targeted practice", "Take practice test mid-week to check progress", "Take final test Friday and compare to pretest for growth measurement"],
      tips: ["Practice writing words from memory, not copying—copying doesn't build recall", "Use spaced repetition: study Day 1, Day 3, Day 7 before final test for better retention", "Test in context sentences, not just isolated words—real writing requires contextual spelling", "Take tests in realistic conditions: timed, no notes, no autocorrect", "Keep error log: track patterns in your misspellings to identify rules you need to learn"],
    },
    faq: [
      { q: "What test formats are available?", a: "Traditional oral/written, multiple choice, fill-in-blank, sentence writing, error detection, dictation, word sorts, and homophone selection. Mix formats for comprehensive assessment." },
      { q: "Can I reuse the same word list?", a: "Yes. Generate multiple tests with the same words but different sentences, formats, or question order. Good for pretests and retests." },
      { q: "How are tests graded?", a: "Automatic grading for multiple choice and fill-in-blank. Traditional oral tests include answer keys for manual grading. Set your own pass threshold (70%, 80%, 90%)." },
      { q: "What's the difference between a pretest and final test?", a: "Same words, but pretest is taken before study to identify gaps. Final test after study measures mastery. Compare scores to track growth." },
    ],
    relatedPages: ["/subjects/spelling", "/subjects/spelling/flashcards", "/subjects/spelling/worksheet-generator", "/ai-quiz-generator"],
  },
];
